// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_list: dynamic(() => import("./BlogList")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  rich_text: dynamic(() => import("./RichText")),
};
